services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  dev-server:
    container_name: dev
    build:
      context: front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app

  front:
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  mongo-data:
